name: CI
on:
  push:
    branches:
      - feature/*
      - release/*
      - hotfix/*
env:
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build-paycadoo-call-chalange:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: docker.devticon.com
          username: app
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: docker.devticon.com/paycadoo-call-chalange:${{ env.IMAGE_TAG }}
          build-args: |-
            GITHUB_TOKEN=${{secrets.GH_TOKEN}}
            SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}}
            SENTRY_URL=${{secrets.SENTRY_URL}}
            SENTRY_ORG=${{secrets.SENTRY_ORG}}
            SENTRY_PROJECT=${{secrets.SENTRY_PROJECT}}
  commit:
    runs-on: ubuntu-latest
    needs:
      - build-paycadoo-call-chalange
    steps:
      - uses: actions/checkout@v2
      - uses: fjogeleit/yaml-update-action@main
        with:
          message: Update Image Version to ${{ env.IMAGE_TAG }}
          commitChange: true
          valueFile: helm/values.yaml
          branch: ${{ github.head_ref || github.ref_name }}
          changes: |-
            {
              "image.name": "docker.devticon.com/paycadoo-call-chalange",
              "image.tag": "${{ env.IMAGE_TAG }}"
            }
